# Generated by Django 3.1.3 on 2021-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20210926_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_ID',
            field=models.IntegerField(),
        ),
    ]
