# Generated by Django 3.1.3 on 2021-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_sale_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_ID',
            field=models.IntegerField(),
        ),
    ]
