# Generated by Django 3.1.3 on 2021-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_auto_20210926_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_date',
            field=models.IntegerField(),
        ),
    ]
