# Generated by Django 3.1.3 on 2021-09-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_auto_20210926_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_ID',
            field=models.DateTimeField(),
        ),
    ]
